spring:
  ## database connection
  datasource:
    platform: H2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cdp
    username: ${DB_USERNAME:sa}

  jpa:
    show-sql: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: create-drop
    properties:
      jdbc:
        batch_size: 500
  sql:
    init:
      mode: never
      platform: h2
  h2:
    console:
      enabled: true